/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as howToFormRouteImport } from './routes/(how-to)/form'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClerksIndexRouteImport } from './routes/_app/clerks/index'
import { Route as AppElectionsIndexRouteImport } from './routes/_app/elections/index'
import { Route as AppElectionsIdBuilderRouteImport } from './routes/_app/elections/$id/builder'
import { Route as AppElectionsIdResultsRouteImport } from './routes/_app/elections/$id/results'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const howToFormRoute = howToFormRouteImport.update({
  id: '/(how-to)/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClerksIndexRoute = AppClerksIndexRouteImport.update({
  id: '/clerks/',
  path: '/clerks/',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionsIndexRoute = AppElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionsIdBuilderRoute = AppElectionsIdBuilderRouteImport.update({
  id: '/elections/$id/builder',
  path: '/elections/$id/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionsIdResultsRoute = AppElectionsIdResultsRouteImport.update({
  id: '/elections/$id/results',
  path: '/elections/$id/results',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof authLoginRoute
  '/form': typeof howToFormRoute
  '/clerks/': typeof AppClerksIndexRoute
  '/elections/': typeof AppElectionsIndexRoute
  '/elections/$id/builder': typeof AppElectionsIdBuilderRoute
  '/elections/$id/results': typeof AppElectionsIdResultsRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/form': typeof howToFormRoute
  '/': typeof AppIndexRoute
  '/clerks': typeof AppClerksIndexRoute
  '/elections': typeof AppElectionsIndexRoute
  '/elections/$id/builder': typeof AppElectionsIdBuilderRoute
  '/elections/$id/results': typeof AppElectionsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(how-to)/form': typeof howToFormRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clerks/': typeof AppClerksIndexRoute
  '/_app/elections/': typeof AppElectionsIndexRoute
  '/_app/elections/$id/builder': typeof AppElectionsIdBuilderRoute
  '/_app/elections/$id/results': typeof AppElectionsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/form'
    | '/clerks/'
    | '/elections/'
    | '/elections/$id/builder'
    | '/elections/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/form'
    | '/'
    | '/clerks'
    | '/elections'
    | '/elections/$id/builder'
    | '/elections/$id/results'
  id:
    | '__root__'
    | '/_app'
    | '/(auth)/login'
    | '/(how-to)/form'
    | '/_app/'
    | '/_app/clerks/'
    | '/_app/elections/'
    | '/_app/elections/$id/builder'
    | '/_app/elections/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  howToFormRoute: typeof howToFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(how-to)/form': {
      id: '/(how-to)/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof howToFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clerks/': {
      id: '/_app/clerks/'
      path: '/clerks'
      fullPath: '/clerks/'
      preLoaderRoute: typeof AppClerksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/elections/': {
      id: '/_app/elections/'
      path: '/elections'
      fullPath: '/elections/'
      preLoaderRoute: typeof AppElectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/elections/$id/builder': {
      id: '/_app/elections/$id/builder'
      path: '/elections/$id/builder'
      fullPath: '/elections/$id/builder'
      preLoaderRoute: typeof AppElectionsIdBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/elections/$id/results': {
      id: '/_app/elections/$id/results'
      path: '/elections/$id/results'
      fullPath: '/elections/$id/results'
      preLoaderRoute: typeof AppElectionsIdResultsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClerksIndexRoute: typeof AppClerksIndexRoute
  AppElectionsIndexRoute: typeof AppElectionsIndexRoute
  AppElectionsIdBuilderRoute: typeof AppElectionsIdBuilderRoute
  AppElectionsIdResultsRoute: typeof AppElectionsIdResultsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClerksIndexRoute: AppClerksIndexRoute,
  AppElectionsIndexRoute: AppElectionsIndexRoute,
  AppElectionsIdBuilderRoute: AppElectionsIdBuilderRoute,
  AppElectionsIdResultsRoute: AppElectionsIdResultsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  authLoginRoute: authLoginRoute,
  howToFormRoute: howToFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
