import { manipulateAsync, SaveFormat } from "expo-image-manipulator";
import { decode } from "jpeg-js";
import { calculateImageMetrics } from "./image-metrics";
import { QUALITY_THRESHOLDS } from "./image-quality-thresholds";
import { IMAGE_QUALITY_MESSAGES } from "./image-quality-messages";

export {
  hasProperLighting,
  hasSufficientContrast,
  isSharpEnough
} from "./image-quality-thresholds";
export type { ImageMetrics } from "./image-metrics";

export interface ImageQualityResult {
  isGoodEnough: boolean;
  brightness: number;
  contrast: number;
  sharpness: number;
  resolution: { width: number; height: number };
  issues: string[];
  warnings: string[];
}

interface DecodedImage {
  width: number;
  height: number;
  data: Uint8Array;
}

/**
 * The analysis image is deliberately much smaller than the upload image. It is
 * large enough to detect page-level blur and lighting problems, while keeping
 * JPEG decoding cheap on older phones.
 */
const MAX_ANALYSIS_DIMENSION = 512;

/**
 * Thresholds are based on the metrics returned by calculateImageMetrics:
 * brightness is luminance (0-255), while contrast and sharpness are scores
 * from 0-100.
 */
const { minBrightness, maxBrightness, minContrast, minSharpness, minWidth, minHeight } =
  QUALITY_THRESHOLDS;

function decodeBase64(base64: string): Uint8Array {
  if (typeof atob !== "function") {
    throw new Error(IMAGE_QUALITY_MESSAGES.base64DecodingUnavailable);
  }

  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);

  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }

  return bytes;
}

function decodeJpeg(base64: string): DecodedImage {
  const decoded = decode(decodeBase64(base64), {
    useTArray: true,
    formatAsRGBA: false,
    maxResolutionInMP: 2,
    maxMemoryUsageInMB: 32
  });

  return {
    width: decoded.width,
    height: decoded.height,
    data: decoded.data
  };
}

/**
 * Analyze image quality on the device before a scan is accepted.
 *
 * Resolution is read from the provided size param. Pixel metrics are calculated
 * from a bounded JPEG generated by Expo so the uploaded image is never
 * replaced or recompressed by the quality check.
 */
export async function analyzeImageQuality(
  uri: string,
  size: { width: number; height: number }
): Promise<ImageQualityResult> {
  const issues: string[] = [];
  const warnings: string[] = [];

  try {
    const { width, height } = size;
    if (!width || !height) throw new Error(IMAGE_QUALITY_MESSAGES.noDimensions);

    const analysisScale = Math.min(1, MAX_ANALYSIS_DIMENSION / Math.max(width, height));
    const analysis = await manipulateAsync(
      uri,
      analysisScale < 1
        ? [{ resize: { width: Math.max(1, Math.round(width * analysisScale)) } }]
        : [],
      { compress: 0.8, format: SaveFormat.JPEG, base64: true }
    );

    if (!analysis.base64) throw new Error(IMAGE_QUALITY_MESSAGES.noPixelData);

    const decoded = decodeJpeg(analysis.base64);
    const { brightness, contrast, sharpness } = calculateImageMetrics(
      decoded.data,
      decoded.width,
      decoded.height,
      3
    );

    if (width < minWidth || height < minHeight) {
      issues.push(IMAGE_QUALITY_MESSAGES.resolutionTooLow(width, height));
    }

    if (brightness < minBrightness) {
      issues.push(IMAGE_QUALITY_MESSAGES.imageToDark);
    } else if (brightness > maxBrightness) {
      issues.push(IMAGE_QUALITY_MESSAGES.imageToBright);
    }

    if (contrast < minContrast) {
      issues.push(IMAGE_QUALITY_MESSAGES.lowContrast);
    }

    if (sharpness < minSharpness) {
      issues.push(IMAGE_QUALITY_MESSAGES.imageBlurry);
    }

    if (width < minWidth * 1.2 || height < minHeight * 1.2) {
      warnings.push(IMAGE_QUALITY_MESSAGES.considerMovingCloser);
    }

    if (brightness < minBrightness + 15 || brightness > maxBrightness - 15) {
      warnings.push(IMAGE_QUALITY_MESSAGES.lightingBorderline);
    }

    if (contrast < minContrast + 15) {
      warnings.push(IMAGE_QUALITY_MESSAGES.contrastBorderline);
    }

    return {
      isGoodEnough: issues.length === 0,
      brightness,
      contrast,
      sharpness,
      resolution: { width, height },
      issues,
      warnings
    };
  } catch (error) {
    console.error("Failed to analyze image quality:", error);

    return {
      isGoodEnough: false,
      brightness: 0,
      contrast: 0,
      sharpness: 0,
      resolution: { width: 0, height: 0 },
      issues: [IMAGE_QUALITY_MESSAGES.analysisError],
      warnings: []
    };
  }
}
